#!/usr/bin/env python
# -*- coding: CP1252 -*-
#
# generated by wxGlade 0.6.8 (standalone edition) on Wed Oct 23 21:29:05 2013
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class ScanSelectionFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.label_ASL = wx.StaticText(self, wx.ID_ANY, _("    ASL processing"))
        self.checkbox_ASL = wx.CheckBox(self, wx.ID_ANY, _("T1/T1app fitting and perfusion calc"))
        self.label_2 = wx.StaticText(self, wx.ID_ANY, _("Inversion times"))
        self.label_3 = wx.StaticText(self, wx.ID_ANY, _("#TI"))
        self.spin_ctrl_TI = wx.SpinCtrl(self, wx.ID_ANY, "14", min=0, max=100)
        self.label_4 = wx.StaticText(self, wx.ID_ANY, _("TI:"))
        self.text_ctrl_TI = wx.TextCtrl(self, wx.ID_ANY, _("300, 500, 700, 900, 1100, 1300, 1500, 1700, 2000, 2300, 2700, 3000, 3500, 4000"), style=wx.TE_MULTILINE)
        self.label_T2 = wx.StaticText(self, wx.ID_ANY, _("    T2 processing"))
        self.checkbox_T21 = wx.CheckBox(self, wx.ID_ANY, _("Fit wth noise offset"))
        self.checkbox_T22 = wx.CheckBox(self, wx.ID_ANY, _("Fit without noise offset"))
        self.label_Dif = wx.StaticText(self, wx.ID_ANY, _("    Diffusion processing"))
        self.checkbox_DTI1 = wx.CheckBox(self, wx.ID_ANY, _("Diffusion tensor fit"))
        self.label_5 = wx.StaticText(self, wx.ID_ANY, _("Tool developed by Kristof Govaerts\n(kristof.govaerts@med.kuleuven.be)"))
        self.label_7 = wx.StaticText(self, wx.ID_ANY, _("Files"))
        self.label_8 = wx.StaticText(self, wx.ID_ANY, _("Scan types"))
        self.label_9 = wx.StaticText(self, wx.ID_ANY, _("Reco number"))
        self.list_box_7 = wx.ListBox(self, wx.ID_ANY, choices=[])
        self.list_box_8 = wx.ListBox(self, wx.ID_ANY, choices=[])
        self.list_box_9 = wx.ListBox(self, wx.ID_ANY, choices=[])
        self.text_ctrl_1 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.browseButton = wx.Button(self, wx.ID_ANY, _("Browse..."))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(_("wxScanSelection"))
        self.SetBackgroundColour(wx.Colour(216, 216, 191))
        self.label_ASL.SetMinSize((200, 20))
        self.label_ASL.SetBackgroundColour(wx.Colour(216, 216, 191))
        self.checkbox_ASL.SetMinSize((200, 20))
        self.label_2.SetMinSize((200, 20))
        self.label_3.SetMinSize((30, 20))
        self.spin_ctrl_TI.SetMinSize((170, 20))
        self.label_4.SetMinSize((30, 20))
        self.label_4.SetBackgroundColour(wx.Colour(216, 216, 191))
        self.text_ctrl_TI.SetMinSize((170, 60))
        self.label_T2.SetMinSize((200, 20))
        self.checkbox_T21.SetMinSize((200, 20))
        self.checkbox_T22.SetMinSize((200, 20))
        self.label_Dif.SetMinSize((200, 20))
        self.label_7.SetMinSize((200, 20))
        self.label_8.SetMinSize((200, 20))
        self.label_9.SetMinSize((150, 20))
        self.list_box_7.SetMinSize((200, 400))
        self.list_box_8.SetMinSize((200, 400))
        self.list_box_9.SetMinSize((100, 400))
        self.text_ctrl_1.SetMinSize((400, 20))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        grid_sizer_1 = wx.FlexGridSizer(2, 2, 0, 0)
        grid_sizer_3 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_2 = wx.FlexGridSizer(2, 3, 0, 0)
        grid_sizer_4 = wx.FlexGridSizer(5, 1, 0, 0)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_5 = wx.FlexGridSizer(2, 2, 0, 0)
        grid_sizer_4.Add((200, 40), 0, 0, 0)
        sizer_1.Add(self.label_ASL, 0, 0, 0)
        sizer_1.Add(self.checkbox_ASL, 0, 0, 0)
        sizer_1.Add(self.label_2, 0, 0, 0)
        grid_sizer_5.Add(self.label_3, 0, 0, 0)
        grid_sizer_5.Add(self.spin_ctrl_TI, 0, 0, 0)
        grid_sizer_5.Add(self.label_4, 0, 0, 0)
        grid_sizer_5.Add(self.text_ctrl_TI, 0, 0, 0)
        sizer_1.Add(grid_sizer_5, 1, wx.EXPAND, 0)
        grid_sizer_4.Add(sizer_1, 1, wx.ALL | wx.EXPAND, 0)
        grid_sizer_4.Add((200, 20), 0, 0, 0)
        sizer_2.Add(self.label_T2, 0, 0, 0)
        sizer_2.Add(self.checkbox_T21, 0, 0, 0)
        sizer_2.Add(self.checkbox_T22, 0, 0, 0)
        grid_sizer_4.Add(sizer_2, 1, wx.ALL | wx.EXPAND, 0)
        grid_sizer_4.Add((200, 20), 0, 0, 0)
        sizer_3.Add(self.label_Dif, 0, 0, 0)
        sizer_3.Add(self.checkbox_DTI1, 0, 0, 0)
        sizer_3.Add((200, 50), 0, 0, 0)
        grid_sizer_4.Add(sizer_3, 1, wx.EXPAND, 0)
        grid_sizer_4.Add(self.label_5, 0, 0, 0)
        grid_sizer_1.Add(grid_sizer_4, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.label_7, 0, 0, 0)
        grid_sizer_2.Add(self.label_8, 0, 0, 0)
        grid_sizer_2.Add(self.label_9, 0, 0, 0)
        grid_sizer_2.Add(self.list_box_7, 0, 0, 0)
        grid_sizer_2.Add(self.list_box_8, 0, wx.EXPAND, 0)
        grid_sizer_2.Add(self.list_box_9, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)
        grid_sizer_1.Add((200, 30), 0, 0, 0)
        grid_sizer_3.Add(self.text_ctrl_1, 0, 0, 0)
        grid_sizer_3.Add(self.browseButton, 0, 0, 0)
        grid_sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)
        self.SetSizer(grid_sizer_1)
        grid_sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class MyFrame
if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    wxScanSelection = MyFrame(None, wx.ID_ANY, "")
    app.SetTopWindow(wxScanSelection)
    wxScanSelection.Show()
    app.MainLoop()